### ISSUE TITLE
drawImage is not showing images after trying at various paths.

### ISSUE THREAD

**Issue by prashantsaini1** [GrupoW2ABrasil/PDFGenerator#1]
Can you please post an Alloy or Classic example of drawImage() method as it seems not working?

I tried all available Filesystem directories and it's not taking up images from any location. I also tried copying an image to documents directory as you have mentioned in app.js example, but nothing is working.

Below code snippet should work as per your example, but it doesn't as well.

    var F = Ti.Filesystem;
    
    // this png file exists in my 'app -> assets -> images' directory
    var file = F.getFile(F.resourcesDirectory, '/images/maf_logo.png');

    var pdfLogo = F.getFile(F.getApplicationDataDirectory(), 'logo.png');
    
    if ( pdfLogo.write( file.read() ) ) {
        return pdfLogo.nativePath;
    } else {
        return "";
    }

**Comment by GrupoW2ABrasil** [comment]
I checked and it works correctly, I'm also using it in 3 projects in production.

```javascript
// this example copy the image from assets to application directory and then draws it
var fileBlob = Ti.UI.createImageView({
    image : 'images/maf_logo.png'
}).toBlob();

var file = Ti.Filesystem.getFile(Titanium.Filesystem.getApplicationDataDirectory(), "maf_logo.png");

file.write(fileBlob);
file.remoteBackup = false;

// draws the image on the top right corner with 80x80
if(file.exists()) {
   pdfGenerator.drawImage(file.nativePath, pdfGenerator.getPageWidth() - 105, 20, 80, 80);
} else {
   Ti.API.info("Oh damn! my image was not created or was not found.");
}
```

```javascript
// this example draws an existent image in application directory
var imagePath = Ti.Filesystem.applicationDataDirectory + 'images' + Ti.Filesystem.separator;
var file = Ti.Filesystem.getFile(imagePath, "maf_logo.png");

// draws the image on the top right corner with 80x80
if(file.exists()) {
   pdfGenerator.drawImage(file.nativePath, pdfGenerator.getPageWidth() - 105, 20, 80, 80);
} else {
   Ti.API.info("Oh damn! my image was not found.");
}
```

If there is no error logs your image was not found or the location of the drew image is out of bounds of the page.

So please, verify if

- The image is in your documents directory (check emulator folders)
- You're drawing the image in a visible location inside the page (see getPageWidth() and getPageHeight() if needed)
- You're using an image file that uses a standard image format such as PNG, JPEG or BITMAP
